### ISSUE TITLE
Esp32 c3

### ISSUE THREAD

**Issue by TysonAdmin** [MoonModules/WLED#19] opened 2023-02-16 15:25 UTC
Hey, I just got a seed studio esp32 c3 off amazon and put weld on it. I was wondering if you could make a version for it. here is the Aircoookie Esp c3 stuff https://github.com/srg74/WLED-wemos-shield/tree/master/resources/Firmware/%40Aircoookie/v0.14.0-b2/S2_S3_C3

Thanks!

**Comment by srg74** [comment] 2023-02-16 16:29
Is Aircoookie firmware works for you?

**Comment by TysonAdmin** [comment] 2023-02-17 17:42
What do you mean? yes, i just want a sound reactive version for esp 32 c3

**Comment by softhack007** [comment] 2023-02-17 20:43
Our -C3 buildenv [[env:esp32c3dev_4MB_max](https://github.com/MoonModules/WLED/blob/da3acc4627e09adfd756b8a06d3403bb2d245673/platformio.ini#L1242)] could work for you, if you have
- at least 4MB Flash
- no PSRAM

**Comment by softhack007** [comment] 2023-02-17 20:57
> i just want a sound reactive version for esp 32 c3

I you already got WLED working on your -C3, then you should indeed use the MoonModules fork for audioreactive. I've recently made some optimization for -C3, so you should have more "fluent" animations, and less lagging behind and other problems with our version.

**Comment by TysonAdmin** [comment] 2023-02-18 19:52
Could you send me a link? I can't find it. (To a bin file I can download)

**Comment by softhack007** [comment] 2023-02-18 20:55
> Could you send me a link? I can't find it. (To a bin file I can download)

Sorry, no pre-compiled bin availeable, so you'll need to build yourself in VSCode (platformio). Considering the experimental nature of -C3 support, this might any way be the better option. We have seem many problems with pre-compiled -C3 firmware that simply won't start (bootlooping) - caused by minor HW differences of the boards.

Maybe @srg74 could you add a build of esp32c3d3v_4MB_max to your repo? @TysTies pre-built firmware may or may not work on -C3, it's not a simple install-and-go as on "classic esp32". If it does not run, then you need to build&upload yourself from VSCode.

**Comment by srg74** [comment] 2023-02-19 06:00
Done.

**Comment by TysonAdmin** [comment] 2023-02-23 19:12
@srg74 Where would I find it?

**Comment by srg74** [comment] 2023-02-23 22:49
> @srg74 Where would I find it?

https://github.com/srg74/WLED-wemos-shield/blob/master/resources/Firmware/%40MoonModules/v0.14.0-b2.19/WLEDMM_0.14.0-b2.19_esp32c3dev_4MB_max.bin

**Comment by softhack007** [comment] 2023-02-24 15:03
@TysTies please close this ticket if the bin above works for you.

**Comment by TysonAdmin** [comment] 2023-02-24 18:00
Thanks!

**Comment by softhack007** [comment] 2023-03-04 14:57
Look like the issue is solved.

**Closed as completed by softhack007** 2023-03-04 14:57 UTC
Labels: enhancement
